---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - git
    - flatpak

    # Environment
    - python3
    - java

    # Utils
    - zsh
    - tilix
    - meld
    - gpaste

    # System settings and tools
    - gnome
    - multibootusb

    # Security tools
    - enpass
