---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - git

    # Environment
    - python3
    - java

    # Utils
    - zsh
    - tilix

    # System settings
    - gnome
