---
# This playbook deploys the whole application stack.

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - git
    - flatpak

    # Environment
    - python3
    - java

    # Utils
    - zsh
    - tilix
    - meld
    - gpaste
    - ulauncher
    - multibootusb

    # System settings and tools
    - gnome

    # Security tools
    - enpass

    # Network
    - chrome

    # Virtual environment
    - docker
    - virtualbox
    - vagrant
