---
# tasks file for {{ cookiecutter.role_name }}
- name: install dependencies
  become: yes
  apt:
    name: "{{ '{{' }} {{ cookiecutter.role_name|replace('-', '_') }}_packages {{ '}}' }}"
    # state: present # by default
