---
# tasks file for zsh
- name: install dependencies
  become: yes
  apt:
    name: "{{ zsh_packages }}"

- name: configure ~/.zshenv
  copy:
    src: .zshenv
    dest: ~/.zshenv

- name: configure ~/.zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc

- name: copy powerlevel10k config
  copy:
    src: .p10k.zsh
    dest: ~/.p10k.zsh

- name: configure ~/.huskyrc
  copy:
    src: .huskyrc
    dest: ~/.huskyrc

# "username" variable is defined in "common" role
- name: Set zsh as default shell
  user:
    name: "{{ username.stdout }}"
    shell: /bin/zsh
  become: true
