---
# tasks file for zsh

# https://github.com/dvorka/hstr/blob/master/INSTALLATION.md#ubuntu
- name: add HSTR PPA
  become: yes
  apt_repository:
    repo: ppa:ultradvorka/ppa
    update_cache: yes
    state: present

- name: install dependencies
  become: yes
  apt:
    name: "{{ zsh_packages }}"

- name: check that the zplugin exists
  stat:
    path: ~/.zplugin/bin/zplugin.zsh
  register: zsh_zplugin_stat_result

- name: install zplugin
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
  when: zsh_zplugin_stat_result.stat.exists == false

- name: configure ~/.zshenv
  copy:
    src: .zshenv
    dest: ~/.zshenv

- name: configure ~/.zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc

- name: copy powerlevel10k config
  copy:
    src: .p10k.zsh
    dest: ~/.p10k.zsh

- name: configure ~/.huskyrc
  copy:
    src: .huskyrc
    dest: ~/.huskyrc

# "username" variable is defined in "common" role
- name: Set zsh as default shell
  user:
    name: "{{ username.stdout }}"
    shell: /bin/zsh
  become: true
