---
# tasks file for enpass
- name: add GPG key
  become: yes
  apt_key:
    url: https://apt.enpass.io/keys/enpass-linux.key
    state: present

- name: add repository
  become: yes
  apt_repository:
    repo: deb https://apt.enpass.io/ stable main
    filename: enpass
    update_cache: yes
    state: present

- name: install dependencies
  become: yes
  apt:
    name: "{{ enpass_packages }}"
