---
# tasks file for enpass
- name: add Enpass key
  become: yes
  apt_key:
    url: https://apt.enpass.io/keys/enpass-linux.key
    state: present

- name: add Enpass repo
  become: yes
  apt_repository:
    repo: deb https://apt.enpass.io/ stable main
    filename: enpass
    update_cache: yes
    state: present

- name: install Enpass
  become: yes
  apt:
    name: "{{ enpass_packages }}"
