---
# tasks file for java

- debug:
    var: java_provider
  changed_when: False

- import_tasks: oracle.yml
  when: java_provider == 'Oracle'
  changed_when: False

- import_tasks: adoptopenjdk.yml
  when: java_provider == 'AdoptOpenJDK'
  changed_when: False
