---
# tasks file for java
- name: add Oracle Java PPA
  become: yes
  apt_repository:
    repo: ppa:linuxuprising/java
    update_cache: yes
    state: present

- name: accept Oracle license
  become: yes
  debconf:
    name: oracle-java12-installer
    question: shared/accepted-oracle-license-v1-2
    value: 'true'
    vtype: select

- name: install dependencies
  become: yes
  apt:
    name: "{{ java_packages }}"
    # state: present # by default
