- name: add Oracle Java Installer repository
  become: yes
  apt_repository:
    repo: ppa:linuxuprising/java
    update_cache: yes
    state: present

- name: accept Oracle Java license
  become: yes
  debconf:
    name: oracle-java14-installer
    question: shared/accepted-oracle-license-v1-2
    value: "true"
    vtype: select

- name: install Oracle Java 14
  become: yes
  apt:
    name: oracle-java14-installer
