- name: add Oracle Java Installer repository
  become: yes
  apt_repository:
    repo: ppa:linuxuprising/java
    update_cache: yes
    state: present

- name: accept Oracle Java license
  become: yes
  debconf:
    name: oracle-java12-installer
    question: shared/accepted-oracle-license-v1-2
    value: 'true'
    vtype: select

- name: install Oracle Java 13
  become: yes
  apt:
    name: oracle-java13-installer
