---
# tasks file for chrome
- name: add Google Chrome key
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: add Google Chrome repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    update_cache: yes
    state: present

- name: install Google Chrome
  become: yes
  apt:
    name: "{{ chrome_packages }}"
