---
# tasks file for chrome
- name: add GPG key
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: add repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    update_cache: yes
    state: present

- name: install dependencies
  become: yes
  apt:
    name: "{{ chrome_packages }}"
