---
# tasks file for virtualbox
- name: accept Virtualbox Extension Pack license
  become: yes
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select

- import_tasks: oracle.yml
  when: virtualbox_provider == 'Oracle'
  changed_when: False

- import_tasks: system.yml
  when: virtualbox_provider == 'System'
  changed_when: False

- name: check that the virtualbox machine's folder exists
  stat:
    path: ~/.local/share/virtualbox-vms
  register: virtualbox_vms_stat_result

- name: create virtualbox machine's folder
  file:
    path: ~/.local/share/virtualbox-vms
    state: directory
    mode: "0755"
  when: virtualbox_vms_stat_result.stat.exists == false

- name: set virtualbox machine's folder
  command: "vboxmanage setproperty machinefolder ~/.local/share/virtualbox-vms"
  changed_when: virtualbox_vms_stat_result.stat.exists == false
