- name: add gpg key 2016
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add gpg key
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: add repository
  become: yes
  apt_repository:
    # repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ lsb_release.stdout }} contrib"
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian disco contrib"
    filename: virtualbox
    update_cache: yes
    state: present

- name: install dependencies
  become: yes
  apt:
    name: "virtualbox-6.0"
