- name: add oracle_vbox_2016 GPG key
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add oracle_vbox GPG key
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: add Oracle Virtualbox repository
  become: yes
  apt_repository:
    # repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ lsb_release.stdout }} contrib"
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian disco contrib"
    filename: virtualbox
    update_cache: yes
    state: present

- name: install Oracle Virtualbox
  become: yes
  apt:
    name: "{{ virtualbox_oracle_packages }}"
  vars:
    virtualbox_oracle_packages:
      - virtualbox-6.1
      # - virtualbox-ext-pack
