---
# tasks file for tilix
- name: install Tilix
  become: yes
  apt:
    name: "{{ tilix_packages }}"

- name: configure Tilix
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/com/gexperts/Tilix/quake-height-percent"
      value: "100"
    - key: "/com/gexperts/Tilix/theme-variant"
      value: "'dark'"
