---
# tasks file for tilix
- name: install dependencies
  become: yes
  apt:
    name: "{{ tilix_packages }}"

- name: Create a symbolic link of VTE configuration
  become: yes
  file:
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh
    state: link

- name: configure Tilix
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/com/gexperts/Tilix/quake-height-percent"
      value: "100"
    - key: "/com/gexperts/Tilix/theme-variant"
      value: "'dark'"
    - key: "/com/gexperts/Tilix/keybindings/terminal-copy"
      value: "'<Ctrl>c'"
    - key: "/com/gexperts/Tilix/keybindings/terminal-paste"
      value: "'<Ctrl>v'"
