---
# tasks file for media
- name: add Celluloid (formerly GNOME MPV) PPA
  become: yes
  apt_repository:
    repo: ppa:xuzhen666/gnome-mpv
    update_cache: yes
    state: present

- name: install dependencies
  become: yes
  apt:
    name: "{{ media_packages }}"
    # state: present # by default
