---
# tasks file for media
- name: install dependencies
  become: yes
  apt:
    name: "{{ media_packages }}"
    # state: present # by default

- name: Install the Celluloid player from flathub
  become: yes
  flatpak:
    name: io.github.celluloid_player.Celluloid
    state: present
